server:
  port:9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.112.133:9300
eureka:
  client:
    service-url: http://localhost:6868/eureka
  instance:
    prefer-ip-address:true