server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://192.168.112.130:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
eureka:
  client:
    service-url: http://localhost:6868/eureka
  instance:
    prefer-ip-address:true