server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.112.133:3306/tensquare_user;characterEncoding=UTF8
    username: root
    password: root

  redis:jpa:
    database: MySQL
    show-sql: true
    host: 192.168.112.133
  rabbitmq:
    host: 192.168.112.133
jwt:
 config:
      key: itcast
      ttl: 360000
eureka:
  client:
    service-url: http://localhost:6868/eureka
  instance:
    prefer-ip-address:true